name: 'Spam Filter'
description: 'Delete or hide comments matching exact messages or from specific users, with built‐in defaults.'
author: 'Louis Maddox'

inputs:
  repo-token:
    description: 'GitHub token (usually provided via the GITHUB_TOKEN secret).'
    required: true

  mode:
    description: 'Action to take: `delete` or `hide`.'
    required: true
    default: 'delete'
    options:
      - delete
      - hide

  disable-default-blocklist:
    description: 'Set to `true` to ignore the built-in defaults entirely.'
    required: false
    default: 'false'

  config-file:
    description: |
      Path to a **JSON or YAML** file in your repo that **must** contain two top-level arrays:
      ```yaml
      users:
        - alice
        - bob

      messages:
        - "Exact message one."
        - "Exact message two!"
      ```
    required: false
    default: '.github/spam-filter-config.yml'

  classifier:
    description: |
      When hiding comments, GraphQL `minimizeComment` classifier (e.g. `OUTDATED`, `RESOLVED`).
    required: false
    default: 'OUTDATED'

runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'trash'
  color: 'red'
