name: Anti-Spam Filter

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  remove_spam:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run spam filter
        uses: lmmx/anti-spam-bot-action@test-v7    # or @v1 for published release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          mode: delete                                # or 'hide' or 'edit'
          # disable-default-blocklist: 'true'        # uncomment to skip built-ins
          config-file: .github/spam-filter-config.yml
          classifier: OUTDATED                        # only needed for 'hide' mode

  check_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Dependency Review # test
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
