name: Anti-Spam Filter

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  remove_spam:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run spam filter
        uses: your-org/spam-filter-action@test-v1    # or @v1 for your published release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          mode: delete                                # or 'hide'
          # disable-default-blocklist: 'true'        # uncomment to skip built-ins
          config-file: .github/spam-filter-config.yml
          classifier: OUTDATED                        # only needed for 'hide' mode
